# Generated by Django 3.0.3 on 2020-02-13 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category')),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True, verbose_name='subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(blank=True, choices=[('IN QUEUE', 'IN QUEUE'), ('ASSIGNED', 'ASSIGNED'), ('PROCESSING', 'PROCESSING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('TRANSFERED', 'TRANSFERED'), ('ADDITIONAL INFO', 'ADDITIONAL INFO')], default='IN QUEUE', max_length=255, null=True, verbose_name='Status')),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateTimeField(null=True)),
                ('extra', models.CharField(blank=True, max_length=1024, null=True, verbose_name='extra')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='ticket.Category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('waiting_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='waiting_for', to=settings.AUTH_USER_MODEL, verbose_name='Waiting For')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('title', models.CharField(max_length=200, verbose_name='CommentTitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='CommentDetail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.ServiceRequest', verbose_name='ServiceRequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
