# Generated by Django 3.0.3 on 2020-02-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200213_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='waiting_for',
        ),
    ]
